CREATE TABLE ADMIN_USER (
    user_id BIGINT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE BLACKLISTED_USER (
    user_id BIGINT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE BLACKLISTED_CHAT (
    chat_id BIGINT PRIMARY KEY
);

CREATE TABLE SETTINGS (
    id VARCHAR(255) PRIMARY KEY,
    data VARCHAR(255)
)