CREATE TABLE BNC_GAME_MESSAGE (
    id IDENTITY NOT NULL PRIMARY KEY,
    game_id BIGINT NOT NULL,
    message_id INT NOT NULL
);

CREATE TABLE BNC_GAME_SAVE (
    id BIGINT PRIMARY KEY,
    game VARCHAR(1000) NOT NULL,
    edit_date TIMESTAMP NOT NULL
);