ALTER TABLE FEEDBACK ALTER COLUMN user_name VARCHAR(255);
ALTER TABLE FEEDBACK ALTER COLUMN chat_title VARCHAR(550);

ALTER TABLE MARRIAGE_REQUEST ALTER COLUMN proposer_name VARCHAR(255);
ALTER TABLE MARRIAGE_REQUEST ALTER COLUMN proposee_name VARCHAR(255);

ALTER TABLE USER_STATS ALTER COLUMN location VARCHAR(255);

ALTER TABLE CHAT_USER ALTER COLUMN name VARCHAR(255);