ALTER TABLE USER_STATS ADD COLUMN name VARCHAR(130);
ALTER TABLE USER_STATS ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CHAT_USER DROP COLUMN name;
ALTER TABLE GENSHIN_CHAT_USER ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
