CREATE TABLE BNC_RECORD(
    `LENGTH` INT NOT NULL CHECK (`LENGTH` BETWEEN 4 AND 16),
    HEXADECIMAL BOOLEAN,
    USER_ID BIGINT NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    TIME_SPENT BIGINT,

    PRIMARY KEY (`LENGTH`, HEXADECIMAL)
);